### ISSUE TITLE
Cant Build with Visual Studion Professional / local pathes in VCXPROJ

### ISSUE THREAD

**Issue by urwiramboll** [Orcina-Ltd/turbine-controllers#1]
I want to compile the project `Bladed controller wrapper\Native controller\build\vs\BladedControllerWrapper.sln` which is failing with the error message

```
c:\mypath\turbine-controllers\Bladed controller wrapper\Native controller\src\Actuator.cpp(1,10): fatal  error C1083: Cannot open include file: 'Actuator.hpp': No such file or directory
```
When I had a look at the VCXPROJ file I saw absolute pathes, which probably will only work on my machine... I tried to change to (e.g.)
```diff
--- a/Bladed controller wrapper/Native controller/build/vs/BladedControllerWrapper.vcxproj	
+++ b/Bladed controller wrapper/Native controller/build/vs/BladedControllerWrapper.vcxproj	
@@ -87,7 +87,7 @@
       <PrecompiledHeader>NotUsing</PrecompiledHeader>
       <PrecompiledHeaderFile>
       </PrecompiledHeaderFile>
-      <AdditionalIncludeDirectories>C:\Development\TurbineControllers\BladedControllerWrapper\Native\include\nlohmann;C:\Development\TurbineControllers\BladedControllerWrapper\Native\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
+      <AdditionalIncludeDirectories>..\include;..\include\nlohmann;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
       <LanguageStandard>stdcpp20</LanguageStandard>
     </ClCompile>
```
which doesnt work. Therefore I wonder if the include files differs or I have just changed the wrong thing.

**Comment by urwiramboll** [comment]
after rereading I realized that the relative path was wrong. can you please add this patch, I am able to compile now.

[inlude_path.patch](https://github.com/Orcina-Ltd/turbine-controllers/files/13175853/inlude_path.patch)

**Comment by davidheff** [comment]
Commit 2fb8a1b8c27289bca1eefb4a4d4aa0aca6f140bf resolves this issue. Thanks for reporting.
